### ISSUE TITLE
Add sendTransactional api method

### ISSUE THREAD

**Issue by apsavin** [s0ph1e/node-expert-sender#2]
Hi, Sophia!

Thank you for such a useful lib.

What to you think about a new method - `sendTransactional`?
Here is the expertsender docs http://manual.expertsender.ru/metody/dejstviya-s-pismami/otpravit-tranzaktsionnoe-soobshchenie-podpischiku

**Comment by s0ph1e** [comment]
Hi Alexander

Thanks for your contribution. I'm going to merge it and create new release

**Comment by s0ph1e** [comment]
Added in release `0.1.1`
